function SingleSineShortSegment(L,f,Fs)
% Compute power spectrum of short segment of sinusoid
% Inputs:
%   L  - sinusoid segment length (default = 64)
%   f  - sinusoid frequency      (default = 61 MHz)
%   Fs - sample rate             (default = 500 MHz)

% This function requires DSP System Toolbox(TM)

% Copyright 2019 The MathWorks, Inc.

% Defaults
if nargin < 1
    % Segment length
    L = 64;
end
if nargin < 2
    % Sinusoid frequency
    f = 61e6;
end
if nargin < 3
    % Sample rate
    Fs = 500e6;
end
% Common Spectrum Analyzer Settings
NAvg = 10;
Ylim = [-20 40];

% Setup Sine Wave
sinewave = dsp.SineWave('Amplitude',3,...
    'Frequency',f,'SamplesPerFrame',L,'SampleRate',Fs);

% Create scopes
rectWinSA = dsp.SpectrumAnalyzer('SampleRate',Fs, ...
    'PlotAsTwoSidedSpectrum',false, ...
    'FrequencyResolutionMethod','WindowLength', ...
    'WindowLength',L, ...
    'Window','Rectangular', ...
    'SpectralAverages',NAvg, ...
    'Title','Rectangular Windowed Spectrum',...
    'PlotType','Stem',...
    'FFTLengthSource','Property',...
    'FFTLength',L,...
    'YLimits',Ylim);
blackmanHarrisSA = dsp.SpectrumAnalyzer('SampleRate',Fs, ...
    'PlotAsTwoSidedSpectrum',false, ...
    'FrequencyResolutionMethod','WindowLength', ...
    'WindowLength',L, ...
    'Window','Blackman-Harris', ...
    'SpectralAverages',NAvg, ...
    'Title','Blackman-Harris Windowed Spectrum',...
    'PlotType','Stem',...
    'FFTLengthSource','Property',...
    'FFTLength',L,...
    'YLimits',Ylim);
filterBankSA = dsp.SpectrumAnalyzer('SampleRate',Fs, ...
    'Method','Filter bank', ...
    'PlotAsTwoSidedSpectrum',false, ...
    'FrequencyResolutionMethod','NumFrequencyBands', ...
    'FFTLengthSource','Property', ...
    'FFTLength',L, ...
    'SpectralAverages',NAvg, ...
    'Title','Filter Bank Spectrum',...
    'PlotType','Stem',...
    'YLimits',Ylim);

tic
while toc < 30
    % Run for 30 seconds
    x = sinewave();
    rectWinSA(x);
    blackmanHarrisSA(x);
    filterBankSA(x);
end
    
    

